(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const r of s.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&c(r)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();document.addEventListener("DOMContentLoaded",()=>{const t=document.querySelector(".subscribe-form"),o=document.querySelector(".modal-overlay"),n=document.querySelector(".close-icon"),c=document.querySelector(".modal-button");t.addEventListener("submit",e=>{e.preventDefault(),t.checkValidity()&&(o.classList.add("is-open"),t.reset())}),[n,c].forEach(e=>{e.addEventListener("click",()=>{o.classList.remove("is-open")})}),o.addEventListener("click",e=>{e.target===o&&o.classList.remove("is-open")}),document.addEventListener("keydown",e=>{e.key==="Escape"&&o.classList.remove("is-open")})});(()=>{const t={openModalBtn:document.querySelector("[data-menu-open]"),closeModalBtn:document.querySelector("[data-menu-close]"),modal:document.querySelector("[data-menu]"),link:document.querySelectorAll(".mobile-menu-nav-link")};t.openModalBtn.addEventListener("click",o),t.closeModalBtn.addEventListener("click",o),t.link.forEach(n=>n.addEventListener("click",o));function o(){t.modal.classList.toggle("is-open")}})();const i=document.querySelector(".scroll-top");window.addEventListener("scroll",()=>{window.scrollY>500?i.classList.add("is-visible"):i.classList.remove("is-visible")});i.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});window.addEventListener("load",()=>{const t=document.createElement("div");t.className="welcome-screen",t.innerHTML=`
    <div class="welcome-content">
      <h1 class="welcome-title">Welcome to</h1>
      <svg class="welcome-logo" width="84" height="36" aria-label="Company Logo">
        <use href="/images/icons.svg#icon-logo"></use>
      </svg>
      <p class="welcome-text">Savor the Essence of Specialty Coffee</p>
    </div>
  `,document.body.appendChild(t);const o=new Audio("/sounds/jojo-intro.mp3");o.volume=.6,o.play().catch(()=>{const n=()=>{o.play().catch(()=>{}),window.removeEventListener("click",n),window.removeEventListener("keydown",n),window.removeEventListener("touchstart",n)};window.addEventListener("click",n,{once:!0}),window.addEventListener("keydown",n,{once:!0}),window.addEventListener("touchstart",n,{once:!0})}),setTimeout(()=>{t.classList.add("hide")},4500),setTimeout(()=>{t.remove()},5e3)});
//# sourceMappingURL=index.js.map
